### PR TITLE
Add macOS 'JupyterLab' menu and tag Help menu

### PR DESCRIPTION
**Pull request by caesar**
Add the standard entries to the macOS 'JupyterLab' menu, and mark the Help menu as such so that macOS adds the standard search box.

See #127.

### CODE REVIEW

**Comment by caesar** [comment]
Bump…?

**Comment by declanvk** [comment]
Hello @caesar, I'm the new intern working on the electron app. I'm sorry that there hasn't been much activity or response from our side. I looked at your changes and the majority look good to merge.

However, I'm not sure about changing the location of the settings/preference menu item. It would make more sense in the macos environment to follow the standard, but maintaining consistency with the browser environment is also important.

Let me know what you think, and I'm sure we can get this merged in soon.

**Comment by tgeorgeux** [comment]
@declanvk what is that status of this? Does it need to be merged or can it be closed?

**Comment by tgeorgeux** [comment]
Closing this PR as it's been covered in recent PR's Please open an issue if you're still having any trouble!

**Pull request closed without merging**
