### PR TITLE
Start jupyter server in child process and launch render process with token.

### PR DESCRIPTION
**Pull request by lucbouchard1**
This commit fixes issue #12 . The server is launched in a child process and the token is collect using `jupyter notebook list`. The token is then injected into the frontend html using Handlebars.

### CODE REVIEW

**Comment by ddavidebor** [comment]
WOOOOOAH

**Comment by ddavidebor** [comment]
@lucbouchard1 why did you remove electron-prebuilt-compile and used vanilla typescript instead?

**Comment by lucbouchard1** [comment]
@ddavidebor I was having problems with the build and changed it out of frustration. I think I have more of a grip on how to configure it now so I will change it back. I agree it's better with electron-prebuilt-compile. I'll open an issue.

**Comment by ddavidebor** [comment]
For future reference: the issue is https://github.com/jupyterlab/jupyterlab_app/issues/28

**Pull request merged**
