### PR TITLE
Change yarn to npm in TravisCI config

### PR DESCRIPTION
**Pull request by declanvk**

### CODE REVIEW

**Comment by ddavidebor** [comment]
Why?

**Comment by declanvk** [comment]
I was working on a fix for a different branch (#157) and I kept getting failures. I tried to reproduce the changes on my machine using `npm` and I was not able to. I then switched to `yarn` and the same errors popped up.

**Comment by declanvk** [comment]
@ddavidebor Sadly, `npm` did not seem to be the perfect solution to my problems.

If you have any advice, please let me know. If not I'll probably close and delete this branch.

**Comment by declanvk** [comment]
@ddavidebor Would it be possible to chat on gitter or some other platform about this?

**Comment by ddavidebor** [comment]
Yes but I do not think I am the most competent person in the matter here.

I mostly followed CI and app building, I have a limited understanding of
jupyterlab peculiarities regarding all the node modules behind the app.

Il gio 12 apr 2018, 18:46 Declan Kelly <notifications@github.com> ha
scritto:

**Comment by declanvk** [comment]
Closing in favour of new PR.

**Pull request closed without merging**
