### PR TITLE
Store window size at app close so app can be reopened in same state

### PR DESCRIPTION
**Pull request by lucbouchard1**
This PR adds code to store the position/dimensions of the main window when the user quits the app. This allows recreating the window that was open when the user last quit the app.

To do this, I added some generic code that allows easily storing application state (src/main/state.ts). This code will be useful as we add more features that depend on persistent state.

### CODE REVIEW

**Comment by ddavidebor** [comment]
In this PR you're not using the JupyterLab APIs to store the window position and dimention, right ?

**Comment by lucbouchard1** [comment]
@ddavidebor Correct. If we have to wait for the Jupyter server to startup before we can get our window dimensions, it's going to make the render time unbearably slow.

**Comment by ddavidebor** [comment]
Isn't it a simpler solution to set a default window size that looks good with the splash screen, then once jupyter is loaded get the window size from the config and resize the window with the electron [APIs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) just before disabling the splash screen?

We shouldn't duplicate low-level features between jupyter and jupyterlab_app.

**Comment by ddavidebor** [comment]
Also, the directories where the code resides are not writeable once the application is packaged.

**Comment by ddavidebor** [comment]
That said, sooner or later we'll have to store something somewhere that is not a Jupiter process, such as the addresses of remove jupyter servers... :smile:

**Comment by lucbouchard1** [comment]
We'll have to sit down and talk with @ellisonbg and the designers about resizing after the server has started. I really don't think that makes sense because the application doesn't only store the size of the last window, it also stores the position. That means that as soon as the server starts, we would either have to move and resize the window or close the splash window and open a separate window, both of which result in a more jagged transition from splash screen to app. Cameron also did a great job of centering the splash screen logo in any window via CSS, so I don't think that will be an issue. 

The data is being stored in the system-specific application data directory. That directory is found using the electron API. We will not be writing to the directory where the code resides. 

You're right, we will need to store some application state eventually anyway, so I think it makes sense to leverage it here.

**Comment by ddavidebor** [comment]
Yeah i agree also the windows size and position has more to do with the user's PC than the notebook server, especially considering remove jupyter servers

**Comment by nproctor** [comment]
On MacOS, the window size persists when you close and open a new app, but the window doesn't open at all on activate.

**Comment by nproctor** [comment]
The application seems slow to activate. See issue #53.

**Pull request merged**
