### PR TITLE
Fixed various bugs arising from upgrade to Jupyterlab beta release

### PR DESCRIPTION
**Pull request by declanvk**
Issues found:
- [x]  Settings backend no longer works
- [x] Native menus missing
- [ ] Startup animation jittering, possibly caused by starting JupyterLab multiple times.

### CODE REVIEW

**Comment by Wietsedv** [comment]
Great work. I am not authorized to merge this into master, but later today I will submit a PR that is built on top of this which implements extension handling (as in, deferred, disabled and ignored extensions) the same way as the main JupyterLab implementation.

And I am working on a generic solution to use native menus everywhere where Phosphor menus are used. I decided to put this in a separate repository since this is not JupyterLab specific. You'll see a PR that implements this today or later this week.

**Comment by declanvk** [comment]
@Wietsedv are you still getting those errors that you mentioned before?

**Comment by Wietsedv** [comment]
Yes. I removed node_modules and the build directory. Did `npm install` and `npm run build:all`. No errors or warnings in the terminal at any point. Then [this](https://github.com/jupyterlab/jupyterlab/blob/master/packages/shortcuts-extension/src/index.ts#L65) errors gets thrown. Then [this](https://github.com/jupyterlab/jupyterlab/blob/b33eb60ff202d1a9576b85f0255f7c9d2b32355f/packages/docmanager-extension/src/index.ts#L145). Then [this](https://github.com/jupyterlab/jupyterlab/blob/559cddc8af7c9dea34c69a165adceba1846dbccb/packages/notebook-extension/src/index.ts#L496). Then [this](https://github.com/jupyterlab/jupyterlab/blob/b33eb60ff202d1a9576b85f0255f7c9d2b32355f/packages/fileeditor-extension/src/index.ts#L173). And then [this](https://github.com/jupyterlab/jupyterlab/blob/b33eb60ff202d1a9576b85f0255f7c9d2b32355f/packages/codemirror-extension/src/index.ts#L145). And finally [this](https://github.com/jupyterlab/jupyterlab/blob/b33eb60ff202d1a9576b85f0255f7c9d2b32355f/packages/settingeditor/src/settingeditor.ts#L387) one. The last one probably because I have the settings editor open if I remember correctly.

**Comment by declanvk** [comment]
@Wietsedv could you also try cleaning out your settings file, and restarting from defaults. I had a similar issue that was resolved by deleting the file `~/Library/Application\ Support/jupyterlab_app/jupyterlab-application-data` which contains all the settings data. The data in that file is possibly in the incorrect format or corrupted.

**Comment by Wietsedv** [comment]
Thanks! That fixes it. Unfortunately I deleted it without a backup. I guess this might become a problem for other people who have tried release 0.1.1. I don't have time right now to check whether I can break it again by using 0.1.1.

**Comment by declanvk** [comment]
@wietsedv @ellisonbg @timkpaine 
I'd like to go ahead and merge this PR in, even with the stuttering issue that is taking place on the loading screen. I a couple of people reporting in issues (#138) that would be directly fixed by this PR and I'll make the issue of the stutter a separate PR. If any of you would like to give it a final once over review, I would appreciate it.

**Comment by tgeorgeux** [comment]
@declanvk are you still looking to have this merged?

**Comment by declanvk** [comment]
@tgeorgeux Yeah, I just need an approval review from someone with the correct access.

**Comment by tgeorgeux** [comment]
@wietsedv You are named as a reviewer on this, I went ahead and merged this so @declanvk can iterate.

**Pull request merged**
